ModelConfig:
  model_name: TGAT
  device: "cuda:0"
  num_neighbors: 5
  sample_neighbor_strategy: recent
  time_scaling_factor: 1e-6
  num_walk_heads: 8
  num_heads: 1
  num_layers: 2
  num_reg_layers: 1
  hidden_reg_layers_dim: 6
  node_dim: 10
  walk_length: 2
  time_gap: 100
  time_feat_dim: 10
  position_feat_dim: 16
  patch_size: 1
  channel_embedding_dim: 64
  max_input_sequence_length: 32
  dropout: 0.0
  task: regression
  trained_model_path: Saved_models/Generated/TGAT/seed0/TGAT_seed0.pkl
  omit_normalization: True

DataConfig:
  dataset_name: Generated
  folder: Data/generated
  edge_feat_file: /ml_generated.npy
  node_feat_file: /ml_generated_node.npy
  index_file: /ml_generated.csv
  feature_names_file: ""
  node_names_file: /generated_node_names.npy
  is_directed: False

TrainConfig:
  num_epochs: 10000
  batch_size: 2000
  optimizer: Adam
  weight_decay: 0.005
  patience: 100
  learning_rate: 0.001
  val_ratio: 0.15
  test_ratio: 0.15
  num_runs: 1
  test_interval_epochs: 10

TempMEConfig:
  bs: 500
  n_epoch: 100
  out_dim: 40
  hid_dim: 64
  temp: 0.07
  prior_p: 0.3
  lr: 0.001
  drop_out: 0.1
  if_bern: true
  weight_decay: 0.0001
  beta: 0.5
  device: "cuda:0"

TGNNExplainerConfig:
  num_rollouts: 50
  min_atoms: 1