ModelConfig:
  model_name: TGN
  device: "cuda:0"
  num_neighbors: 10
  sample_neighbor_strategy: recent
  time_scaling_factor: 1e-6
  num_walk_heads: 8
  num_heads: 2
  num_layers: 1
  num_reg_layers: 2
  hidden_reg_layers_dim: 172
  node_dim: 172
  walk_length: 2
  time_gap: 100
  time_feat_dim: 100
  position_feat_dim: 16
  patch_size: 1
  channel_embedding_dim: 64
  max_input_sequence_length: 32
  dropout: 0.2
  task: classification
  trained_model_path: Saved_models\\MOOCTGN\\TGN\\TGN_seed0.pkl

DataConfig:
  dataset_name: MOOCTGN
  folder: Data\\MOOC
  edge_feat_file: \\mooc.npy
  node_feat_file: \\mooc_node.npy
  index_file: \\mooc.csv
  feature_names_file: ""
  is_directed: False

TrainConfig:
  num_epochs: 100
  batch_size: 200
  optimizer: Adam
  weight_decay: 0.0
  patience: 15
  learning_rate: 0.0001
  val_ratio: 0.15
  test_ratio: 0.15
  num_runs: 1
  test_interval_epochs: 10

TempMEConfig:
  bs: 500
  n_epoch: 10
  out_dim: 40
  hid_dim: 64
  temp: 0.07
  prior_p: 0.3
  lr: 0.001
  drop_out: 0.1
  if_bern: true
  weight_decay: 0
  beta: 0.5
  device: "cuda:0"

TGNNExplainerConfig:
  num_rollouts: 500
  min_atoms: 20